; PlatformIO Project Configuration File
; Smart Water Quality Monitoring and Automated Response System
; Target: ESP32 DevKit C V4 / esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    mathworks/ThingSpeak@^2.0.0
